gSignalConnect(opcaoCarteiraAbrir, "activate", callbackCarteiraAbrir)
gSignalConnect(opcaoCarteiraNova, "activate", callbackCarteiraNova)
gSignalConnect(subOpcaoCarteiraRecentesLimpar, "activate", callbackCarteiraRecentesLimpar)
gSignalConnect(opcaoCarteiraSair, "activate", callbackCarteiraSair)
gSignalConnect(opcaoCarteiraSalvar, "activate", callbackCarteiraSalvar)
gSignalConnect(opcaoCarteiraSalvarComo, "activate", callbackCarteiraSalvarComo)

gSignalConnect(opcaoSupRes, "activate", callbackEstudoMudaStatus)
gSignalConnect(opcaoBB, "activate", callbackEstudoMudaStatus)
gSignalConnect(opcaoMME, "activate", callbackEstudoMudaStatus)
gSignalConnect(opcaoVF, "activate", callbackEstudoMudaStatus)
gSignalConnect(opcaoMMVF, "activate", callbackEstudoMudaStatus)
gSignalConnect(opcaoIFR, "activate", callbackEstudoMudaStatus)
gSignalConnect(opcaoChAD, "activate", callbackEstudoMudaStatus)
gSignalConnect(opcaoDPO, "activate", callbackEstudoMudaStatus)

gSignalConnect(janelaPrincipal, 'show', callbackJanelaPrincipalActivate)
gSignalConnect(janelaPrincipal, 'delete-event', callbackJanelaPrincipalDestroy)

gSignalConnect(opcaoSimboloAtualizar, "activate", callbackSimboloAtualiza)
gSignalConnect(opcaoSimboloEditar, "activate", callbackSimboloEdita)
gSignalConnect(opcaoSimboloInserir, "activate", callbackSimboloInsere)
gSignalConnect(opcaoSimboloRemover, "activate", callbackSimboloRemove)

gSignalConnect(toolLeft, "clicked", callbackToolMoveChartLeft)
gSignalConnect(toolRight, "clicked", callbackToolMoveChartRight)
gSignalConnect(toolRepaint, "clicked", callbackToolRepaint)
gSignalConnect(toolVariance, "clicked", callbackToolVariance)
gSignalConnect(toolZoomIn, "clicked", callbackToolZoomIn)
gSignalConnect(toolZoomInterval, "clicked", callbackToolZoomInterval)
gSignalConnect(toolZoomFit, "clicked", callbackToolZoomFit)
gSignalConnect(toolZoomOut, "clicked", callbackToolZoomOut)
